os: linux
env: gh-token
dist: focal
language: java
jdk:
  - openjdk8
jobs:
  include: 
  - name: “test123” # existing functionality
    script: # existing functionality
      - java -version
  - name: “sbom”
    script: # existing functionality
      - java -version
      - cd test
      - cat java/java_bom.json
    addons:
      sbom:
        on:
          branch: 'main'
          pr: false
        # condition: false
        run_phase: "before_script"
        output_format: "cyclonedx-json"
        output_dir: "/test"
        input_dir: "/java"      
deploy:
 provider: pages
 skip_cleanup: true
 github_token: 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
 keep_history: true
 on:
   branch: main
